library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(tibble)
library(stringr)
library(ggplot2)
library(xml2)
library(sp)
library(rgdal)
library(rgeos)
library(raster)
library(tidyverse)
library(maptools)
library(cluster)
library(gridExtra)
library(ggpubr)
library(iml)
library(ggalt)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
